### ISSUE TITLE
Writing assets file issue

### ISSUE THREAD

**Issue by samsonradu** [muayyad-alsadi/yii-EClientScript#18]
I have my assets folder containing hundreds of thousands of JS files after running this in production (see screenshot)

![untitled](https://cloud.githubusercontent.com/assets/2971447/8892857/454c1e2e-337b-11e5-9622-e8c0e110074e.png)

ClientScript config is pretty much the default one. Error is: 

<pre>
 file_put_contents() [<a href='function.file-put-contents'>function.file-put-contents</a>]: Only 0 of 65341 bytes written, possibly    out of free disk space (/mnt/storage/www/members.clubseventeen.com/protected/extensions/eclientscript/EClientScript.php:193)
</pre>

<pre>
    'clientScript' => array(
            /*
            'class' => 'ext.eclientscript.EClientScript',
            'combineScriptFiles' => true, // By default this is set to true, set this to true if you'd like to combine the script files
            'combineCssFiles' => true, // By default this is set to true, set this to true if you'd like to combine the css files
            'optimizeScriptFiles' => false, // @since: 1.1
            'optimizeCssFiles' => false, // @since: 1.1
            'optimizeInlineScript' => false, // @since: 1.6, This may case response slower
            'optimizeInlineCss' => false, // @since: 1.6, This may case response slower
            'coreScriptPosition' => 2,
            'defaultScriptFilePosition' => 2,
            'coreScriptPosition' => 2,
            'defaultScriptFilePosition' => 2,
             */
            'scriptMap' => array(
                'jquery.js' => false,
                'jquery.min.js' => false,
                'jquery-ui.js' => false,
                'jquery-ui.min.js' => false,
                'jquery.ba-bbq.js' => false,
                'bootstrap.js' => false,
                'jquery.yiilistview.js' => false,
                'jquery.yiigridview.js' => false,
            )
        ),
</pre>

I assume the $isValid boolean is always false for some reason, requiring a write to disk?

**Comment by muayyad-alsadi** [comment]
It seems that you are out of disk space.

You can safely remove them all and it will create them again.

My suggestion is to serve the bigger files like bootstrap.css and .js from
a cdn and make sure they are not part of client script combined files.

**Comment by samsonradu** [comment]
Well, yes but that's because the extensions thinks one of the JS assets have changed and rewrites the concatenated script every time. 

The <pre>getCombinedFileName()</pre> generates false positives. Any idea why? 

https://github.com/muayyad-alsadi/yii-EClientScript/blob/master/EClientScript.php#L404

Eventually I ll just add a new bool $forceNew and only regenerate the the contatenated file when it's manually set to true (hence making $valid always true)

**Comment by muayyad-alsadi** [comment]
Why would your operating system report wrong modified time (filemtime) ?

If you use archives(zip/tar) to deploy make sure you preserve times.

You had better change your deployment script ex. To use git

**Comment by samsonradu** [comment]
Will check the filemtimes.
I am using git, the files haven t been touched imo.

**Comment by samsonradu** [comment]
http://www.yiiframework.com/doc/api/1.1/CAssetManager#forceCopy-detail

Think this was set to true and the files were being re-published. Fixed.
